name: psa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  cloud_firestore: ^3.1.6
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  firebase_auth: ^3.3.5
  image_picker: ^0.8.4+4
  google_sign_in: ^5.2.3
  firebase_auth_oauth: ^1.1.0
  flutter_snake_navigationbar: ^0.6.0
  bubble: ^1.2.1
  flutter_lints: ^1.0.0
  fancy_containers: ^0.0.3
  direct_select: ^2.0.0
  dropdown_button2: ^1.1.1
  lottie: ^1.2.1
  circular_profile_avatar: ^2.0.5
  flutter_speed_dial: ^5.0.0+1
  url_launcher: ^6.0.18
  material_design_icons_flutter: ^5.0.6595
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  date_util: ^0.1.4
  animated_text_kit: ^4.2.1
  photo_view: ^0.13.0
  flutter_staggered_animations: ^1.0.0
  table_calendar: ^3.0.2
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.0
  mailto: ^2.0.0
  flutter_share: ^2.0.0
  #share_plus: ^3.1.0
  http: ^0.13.4
  rive: ^0.8.1
  #firebase_messaging: ^11.2.8

#  material_design_icons_flutter: 5.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/Lobster-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
